language: android
before_install: cd src
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedCheck --stacktrace
after_failure:
  - cat appstax-android/build/outputs/lint-results-debug.xml
git:
  depth: 10
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-19
branches:
  only:
    - master
