#!/usr/bin/env bash -eu
# Local development deploy

cd "$(dirname "$0")"/..

SOURCE="src/appstax/build/libs/appstax.jar"
TARGET="appstax-android.jar"

ANDROID="dist/$TARGET"
EXAMPLE="examples/basic/app/libs/$TARGET"

pushd src
./gradlew jarRelease
popd

cp $SOURCE $ANDROID
cp $SOURCE $EXAMPLE
